### ISSUE TITLE
Ajouter le support pour les websockets :)

### ISSUE THREAD

**Issue by cthpw103** [jiktim/minitel.js#8]
https://www.goto10.fr/minitel/divers/codeurs-en-seine-minitel.pdf

**Comment by prometheus1337** [comment]
c un truc dan le minitel????????????????????????????

**Comment by tinydraeth** [comment]
creme de la penis

**Comment by prometheus1337** [comment]
dagaropa

**Comment by cthpw103** [comment]
@prometheus1337 non faut pas déconner c'était en 1980..

**Comment by cthpw103** [comment]
c'est pour l'émulateur de Fréderic BISSON

**Comment by tinydraeth** [comment]
au fait taper comme ca c est tres moche @prometheus1337

**Comment by cthpw103** [comment]
c'est vrai

**Comment by cthpw103** [comment]
en gros minitel-over-websocket :)

**Comment by prometheus1337** [comment]
compris

**Comment by prometheus1337** [comment]
@tinydraeth Je cherche mes cles !

**Comment by tinydraeth** [comment]
La vie est belle.

**Comment by prometheus1337** [comment]
![image](https://user-images.githubusercontent.com/44480063/69559366-1df9f980-0faa-11ea-975a-5ebe7c75cd56.png)

**Comment by cthpw103** [comment]
Sinon, si vous allez faire les kékés allez sur Discord..

**Comment by prometheus1337** [comment]
compris

**Comment by tinydraeth** [comment]
github > discord me faire changer d'avis

**Comment by prometheus1337** [comment]
chut @tinydraeth

**Comment by cthpw103** [comment]
je vais vous mute si vous arrêtez pas de faire les kékés

**Comment by tinydraeth** [comment]
d'accord

**Comment by cthpw103** [comment]
Progrès: ca marche, je crois.. write-only :/
